---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

-   hosts: k3s_cluster
    gather_facts: yes
    become: yes
    tasks:
        -   name: copy docker deamon.json
            copy: src=../config/docker-mirror-daemon.json dest=/etc/docker/daemon.json
        -   name: copy k3s containerd mirror config
            copy: src=../config/k3s-containerd.config.toml.tmpl dest=/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
        -   name: increate max_map_count (used for elasticsearch)
            shell: sysctl -w vm.max_map_count=262144